export type JenisTindakan = "Registrasi PSE" | "Routing IAP" | "Escrow Settlement" | "Koordinasi Skema Kartu" | "Insentif Kepatuhan"
export type Institusi = "Kominfo" | "App Store / Play Store" | "PSP" | "Jaringan Kartu Internasional" | "Platform Iklan Digital"
export type GayaInstitusi = "tegas" | "netral" | "lembut"

export type InstitusiInfo = {
  jenisTindakan: JenisTindakan
  deskripsiSingkat: string
  actionLabel: string
  fieldTambahanLabel: string
  leverage: string
  gaya: GayaInstitusi
}

export const institusiConfig: Record<Institusi, InstitusiInfo> = {
  Kominfo: {
    jenisTindakan: "Registrasi PSE",
    deskripsiSingkat: "Kewenangan registrasi Penyelenggara Sistem Elektronik",
    actionLabel: "Ajukan Pemblokiran PSE",
    fieldTambahanLabel: "Status Tanda Daftar PSE",
    leverage: "Tertinggi",
    gaya: "tegas",
  },
  "App Store / Play Store": {
    jenisTindakan: "Routing IAP",
    deskripsiSingkat: "Kewenangan routing in-app purchase dan distribusi aplikasi",
    actionLabel: "Aktifkan Routing IAP Wajib",
    fieldTambahanLabel: "ID Aplikasi di Store",
    leverage: "Tinggi",
    gaya: "tegas",
  },
  PSP: {
    jenisTindakan: "Escrow Settlement",
    deskripsiSingkat: "Kewenangan penahanan dan pencairan dana settlement",
    actionLabel: "Proses Penahanan Settlement",
    fieldTambahanLabel: "Rekening Tujuan Settlement",
    leverage: "Menengah",
    gaya: "netral",
  },
  "Jaringan Kartu Internasional": {
    jenisTindakan: "Koordinasi Skema Kartu",
    deskripsiSingkat: "Jalur cadangan lewat koordinasi dengan jaringan kartu internasional untuk transaksi lintas batas",
    actionLabel: "Ajukan Koordinasi Blokir Skema Kartu",
    fieldTambahanLabel: "Skema Kartu Teridentifikasi",
    leverage: "Menengah-Rendah",
    gaya: "netral",
  },
  "Platform Iklan Digital": {
    jenisTindakan: "Insentif Kepatuhan",
    deskripsiSingkat: "Sinyal deteksi tambahan dan insentif trusted-advertiser bagi platform kooperatif",
    actionLabel: "Kirim Sinyal Insentif Kepatuhan",
    fieldTambahanLabel: "Status Trusted Advertiser",
    leverage: "Terendah (Soft Leverage)",
    gaya: "lembut",
  },
}

export type KasusEskalasi = {
  id: string
  platform: string
  domisili: string
  institusi: Institusi
  catatan: string
  dieskalasi: string
  sisaHari: number
  sumberSinyal: string
  confidenceScore: number
  estimasiGap: string
  petugasDjp: string
  nomorSurat: string
  detailTambahan: string
}

export const antrianAwal: KasusEskalasi[] = [
  {
    id: "esk-1",
    platform: "Kling AI",
    domisili: "Tiongkok",
    institusi: "Kominfo",
    catatan: "Belum merespons notifikasi resmi DJP selama 14 hari. Diminta registrasi PSE Lingkup Privat.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Similarweb",
    confidenceScore: 87,
    estimasiGap: "Rp500 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0142",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-2",
    platform: "NeoPay AI",
    domisili: "Singapura",
    institusi: "PSP",
    catatan: "Transaksi PSP domestik melebihi ambang batas tanpa status pemungut resmi. Diminta penahanan settlement sementara.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 5,
    sumberSinyal: "BI / PSP",
    confidenceScore: 74,
    estimasiGap: "Rp210 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0139",
    detailTambahan: "DBS Bank Singapore ****7734",
  },
  {
    id: "esk-3",
    platform: "VisionCraft",
    domisili: "Korea Selatan",
    institusi: "App Store / Play Store",
    catatan: "Lonjakan unduhan aplikasi tidak diimbangi kepatuhan pajak. Diminta penyesuaian routing in-app purchase.",
    dieskalasi: "28 Jun 2026",
    sisaHari: -1,
    sumberSinyal: "App Store / Play Store",
    confidenceScore: 66,
    estimasiGap: "Rp95 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0131",
    detailTambahan: "com.visioncraft.app",
  },
  {
    id: "esk-4",
    platform: "PromptForge",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Konten teridentifikasi belum memiliki tanda daftar PSE meski aktif dipasarkan di Indonesia.",
    dieskalasi: "22 Jun 2026",
    sisaHari: 8,
    sumberSinyal: "Media Massa",
    confidenceScore: 55,
    estimasiGap: "Rp40 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0118",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-5",
    platform: "DeepSeek",
    domisili: "Tiongkok",
    institusi: "Kominfo",
    catatan: "Adopsi melonjak drastis dalam 10 hari, belum ada tanda registrasi PSE sama sekali.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 1,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 91,
    estimasiGap: "Rp650 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0145",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-6",
    platform: "Runway ML",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Volume transaksi kartu kredit domestik naik tajam, belum ada kejelasan status pemungut.",
    dieskalasi: "30 Jun 2026",
    sisaHari: 3,
    sumberSinyal: "BI / PSP",
    confidenceScore: 68,
    estimasiGap: "Rp290 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0134",
    detailTambahan: "Xendit VA ****2210",
  },
  {
    id: "esk-7",
    platform: "Midjourney Mobile",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi baru rilis di Play Store, unduhan tinggi tapi billing belum di-routing resmi.",
    dieskalasi: "2 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "data.ai",
    confidenceScore: 62,
    estimasiGap: "Rp410 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0140",
    detailTambahan: "com.midjourney.mobile",
  },
  {
    id: "esk-8",
    platform: "ScriptSynth AI",
    domisili: "Kanada",
    institusi: "Kominfo",
    catatan: "Platform text-to-speech AI, konten dipasarkan aktif tapi belum ada tanda daftar PSE.",
    dieskalasi: "18 Jun 2026",
    sisaHari: -6,
    sumberSinyal: "Media Massa",
    confidenceScore: 48,
    estimasiGap: "Rp25 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0109",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-9",
    platform: "PixelMind",
    domisili: "Jepang",
    institusi: "PSP",
    catatan: "Transaksi lewat gerbang pembayaran domestik melebihi ambang batas dua bulan berturut-turut.",
    dieskalasi: "27 Jun 2026",
    sisaHari: 6,
    sumberSinyal: "BI / PSP",
    confidenceScore: 71,
    estimasiGap: "Rp180 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0129",
    detailTambahan: "Doku Merchant ****5588",
  },
  {
    id: "esk-10",
    platform: "VoiceForge",
    domisili: "Inggris",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi voice cloning AI, ranking naik pesat di App Store Indonesia tanpa kejelasan pajak.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 7,
    sumberSinyal: "Similarweb",
    confidenceScore: 59,
    estimasiGap: "Rp70 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0144",
    detailTambahan: "com.voiceforge.app",
  },
  {
    id: "esk-11",
    platform: "Claude AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Chatbot AI generatif dengan basis pengguna besar, belum ada tanda daftar PSE Lingkup Privat.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Similarweb",
    confidenceScore: 82,
    estimasiGap: "Rp720 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0146",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-12",
    platform: "Gemini Advanced",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Integrasi mendalam dengan ekosistem Android, belum ada kejelasan status PSE.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 79,
    estimasiGap: "Rp680 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0147",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-13",
    platform: "Mistral Le Chat",
    domisili: "Prancis",
    institusi: "Kominfo",
    catatan: "Platform AI open-weight, adopsi meningkat di kalangan developer Indonesia.",
    dieskalasi: "24 Jun 2026",
    sisaHari: 10,
    sumberSinyal: "Media Massa",
    confidenceScore: 51,
    estimasiGap: "Rp35 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0121",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-14",
    platform: "Grok AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Chatbot terintegrasi dengan platform media sosial, unduhan aplikasi mandiri melonjak.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "data.ai",
    confidenceScore: 76,
    estimasiGap: "Rp410 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0148",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-15",
    platform: "Copilot Microsoft",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "AI asisten terintegrasi Windows, distribusi luas tanpa status pemungut PPN.",
    dieskalasi: "19 Jun 2026",
    sisaHari: -5,
    sumberSinyal: "Similarweb",
    confidenceScore: 44,
    estimasiGap: "Rp30 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0112",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-16",
    platform: "HeyGen",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform AI video avatar, popularitas naik untuk konten pemasaran digital.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 6,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 61,
    estimasiGap: "Rp150 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0137",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-17",
    platform: "Cohere Command",
    domisili: "Kanada",
    institusi: "Kominfo",
    catatan: "Model bahasa untuk enterprise, mulai digunakan startup lokal tanpa perjanjian resmi.",
    dieskalasi: "26 Jun 2026",
    sisaHari: 9,
    sumberSinyal: "Media Massa",
    confidenceScore: 47,
    estimasiGap: "Rp20 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0125",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-18",
    platform: "You.com",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Mesin pencari berbasis AI, traffic meningkat drastis dalam 2 bulan terakhir.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "Similarweb",
    confidenceScore: 58,
    estimasiGap: "Rp85 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0141",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-19",
    platform: "Ideogram AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform generatif gambar dengan fitur teks presisi, adopsi cepat di komunitas desain.",
    dieskalasi: "29 Jun 2026",
    sisaHari: -3,
    sumberSinyal: "data.ai",
    confidenceScore: 53,
    estimasiGap: "Rp45 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0133",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-20",
    platform: "Leonardo AI",
    domisili: "Australia",
    institusi: "Kominfo",
    catatan: "Platform desain grafis berbasis AI, digunakan luas oleh agensi kreatif lokal.",
    dieskalasi: "20 Jun 2026",
    sisaHari: -4,
    sumberSinyal: "Media Massa",
    confidenceScore: 42,
    estimasiGap: "Rp18 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0114",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-21",
    platform: "Krea AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Editor visual real-time berbasis AI, ranking naik cepat di kalangan konten kreator.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 5,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 60,
    estimasiGap: "Rp95 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0143",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-22",
    platform: "ElevenLabs Reader",
    domisili: "Inggris",
    institusi: "Kominfo",
    catatan: "Aplikasi text-to-speech premium, unduhan naik tajam pasca fitur multi-bahasa Indonesia.",
    dieskalasi: "2 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "data.ai",
    confidenceScore: 69,
    estimasiGap: "Rp160 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0138",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-23",
    platform: "Descript",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform edit audio/video berbasis AI, mulai digunakan tim media & podcaster lokal.",
    dieskalasi: "23 Jun 2026",
    sisaHari: 8,
    sumberSinyal: "Media Massa",
    confidenceScore: 39,
    estimasiGap: "Rp15 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0119",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-24",
    platform: "Pi AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Chatbot AI personal companion, komunitas pengguna aktif tumbuh signifikan.",
    dieskalasi: "17 Jun 2026",
    sisaHari: -7,
    sumberSinyal: "Similarweb",
    confidenceScore: 36,
    estimasiGap: "Rp12 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0107",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-25",
    platform: "Replika",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Aplikasi AI companion, basis pengguna stabil namun belum ada status PSE.",
    dieskalasi: "21 Jun 2026",
    sisaHari: -2,
    sumberSinyal: "data.ai",
    confidenceScore: 45,
    estimasiGap: "Rp22 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0116",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-26",
    platform: "Tabnine",
    domisili: "Israel",
    institusi: "Kominfo",
    catatan: "AI code assistant, adopsi tinggi di kalangan developer software house lokal.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "Media Massa",
    confidenceScore: 33,
    estimasiGap: "Rp10 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0149",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-27",
    platform: "Cursor AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Editor kode berbasis AI, ranking unduhan naik pesat di kalangan startup teknologi.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 5,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 72,
    estimasiGap: "Rp380 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0150",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-28",
    platform: "Windsurf AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "IDE berbasis AI baru, tingkat adopsi tim engineering lokal meningkat cepat.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 0,
    sumberSinyal: "data.ai",
    confidenceScore: 56,
    estimasiGap: "Rp70 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0136",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-29",
    platform: "Lovable AI",
    domisili: "Swedia",
    institusi: "Kominfo",
    catatan: "Platform pembuatan aplikasi berbasis prompt, tren digunakan oleh startup pemula.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Similarweb",
    confidenceScore: 64,
    estimasiGap: "Rp130 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0142B",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-30",
    platform: "Bolt.new",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform pengembangan web berbasis AI, digunakan agensi kreatif untuk prototipe cepat.",
    dieskalasi: "28 Jun 2026",
    sisaHari: -1,
    sumberSinyal: "Media Massa",
    confidenceScore: 41,
    estimasiGap: "Rp17 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0130",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-31",
    platform: "v0 by Vercel",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Tool generatif UI berbasis AI, tren pemakaian naik di komunitas developer frontend.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "data.ai",
    confidenceScore: 49,
    estimasiGap: "Rp28 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0144B",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-32",
    platform: "Manus AI",
    domisili: "Tiongkok",
    institusi: "Kominfo",
    catatan: "AI agent otonom untuk tugas kompleks, popularitas melonjak pasca peluncuran global.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 85,
    estimasiGap: "Rp590 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0151",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-33",
    platform: "Genspark AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform pencarian & pembuatan konten AI, traffic dari Indonesia meningkat pesat.",
    dieskalasi: "25 Jun 2026",
    sisaHari: 11,
    sumberSinyal: "Similarweb",
    confidenceScore: 37,
    estimasiGap: "Rp13 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0123",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-34",
    platform: "DeepL Write",
    domisili: "Jerman",
    institusi: "Kominfo",
    catatan: "Alat penerjemahan & penulisan berbasis AI, digunakan luas kalangan korporat.",
    dieskalasi: "18 Jun 2026",
    sisaHari: -6,
    sumberSinyal: "Media Massa",
    confidenceScore: 40,
    estimasiGap: "Rp16 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0110",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-35",
    platform: "Poe by Quora Mobile",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Agregator model AI multi-chatbot, aplikasi mandiri tumbuh cepat di App Store.",
    dieskalasi: "2 Jul 2026",
    sisaHari: 1,
    sumberSinyal: "data.ai",
    confidenceScore: 54,
    estimasiGap: "Rp60 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0139B",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-36",
    platform: "Hume AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Model AI pengenalan emosi suara, mulai diadopsi startup customer service lokal.",
    dieskalasi: "22 Jun 2026",
    sisaHari: -5,
    sumberSinyal: "Media Massa",
    confidenceScore: 31,
    estimasiGap: "Rp9 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0117",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-37",
    platform: "Fireflies AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Asisten notulen rapat berbasis AI, tren pemakaian tinggi di perusahaan multinasional.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Similarweb",
    confidenceScore: 46,
    estimasiGap: "Rp24 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0145B",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-38",
    platform: "Otter.ai",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Transkripsi rapat otomatis berbasis AI, banyak dipakai tim korporat dan media.",
    dieskalasi: "19 Jun 2026",
    sisaHari: -8,
    sumberSinyal: "data.ai",
    confidenceScore: 43,
    estimasiGap: "Rp19 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0113",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-39",
    platform: "Synthesys AI",
    domisili: "Singapura",
    institusi: "Kominfo",
    catatan: "Platform sulih suara & video AI, ekspansi cepat di pasar Asia Tenggara termasuk Indonesia.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 1,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 57,
    estimasiGap: "Rp88 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0135",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-40",
    platform: "Vectara AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform RAG enterprise, mulai digunakan lembaga finansial lokal untuk chatbot internal.",
    dieskalasi: "24 Jun 2026",
    sisaHari: -9,
    sumberSinyal: "Media Massa",
    confidenceScore: 29,
    estimasiGap: "Rp7 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0120",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-41",
    platform: "Rewind AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Aplikasi asisten memori digital berbasis AI, ranking naik pesat di komunitas produktivitas.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "data.ai",
    confidenceScore: 63,
    estimasiGap: "Rp140 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0152",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-42",
    platform: "Adept AI",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "AI agent untuk otomasi tugas digital kompleks, pilot project dengan beberapa korporat lokal.",
    dieskalasi: "20 Jun 2026",
    sisaHari: -10,
    sumberSinyal: "Media Massa",
    confidenceScore: 35,
    estimasiGap: "Rp11 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0115",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-43",
    platform: "Writesonic",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Platform penulisan konten pemasaran berbasis AI, populer di kalangan UMKM digital.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Similarweb",
    confidenceScore: 52,
    estimasiGap: "Rp50 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0142C",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-44",
    platform: "Copy.ai",
    domisili: "Amerika Serikat",
    institusi: "Kominfo",
    catatan: "Alat pembuatan copywriting berbasis AI, adopsi luas di kalangan pelaku bisnis digital.",
    dieskalasi: "21 Jun 2026",
    sisaHari: -11,
    sumberSinyal: "data.ai",
    confidenceScore: 38,
    estimasiGap: "Rp14 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0117B",
    detailTambahan: "Belum terdaftar (status: kosong)",
  },
  {
    id: "esk-45",
    platform: "Perplexity AI",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi pencarian AI, unduhan tinggi di Play Store namun billing belum di-routing resmi.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 74,
    estimasiGap: "Rp320 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0153",
    detailTambahan: "ai.perplexity.app",
  },
  {
    id: "esk-46",
    platform: "Character.AI",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi chatbot AI karakter, basis pengguna remaja besar, routing IAP belum resmi.",
    dieskalasi: "2 Jul 2026",
    sisaHari: -2,
    sumberSinyal: "data.ai",
    confidenceScore: 68,
    estimasiGap: "Rp275 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0154",
    detailTambahan: "ai.character.app",
  },
  {
    id: "esk-47",
    platform: "Suno AI",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi pembuat musik AI, unduhan melonjak drastis pasca fitur kolaborasi baru.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Similarweb",
    confidenceScore: 61,
    estimasiGap: "Rp190 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0155",
    detailTambahan: "com.suno.app",
  },
  {
    id: "esk-48",
    platform: "Udio",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi generatif musik AI, ranking naik cepat di App Store kalangan musisi indie.",
    dieskalasi: "19 Jun 2026",
    sisaHari: -7,
    sumberSinyal: "data.ai",
    confidenceScore: 39,
    estimasiGap: "Rp21 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0156",
    detailTambahan: "com.udio.app",
  },
  {
    id: "esk-49",
    platform: "CapCut AI",
    domisili: "Tiongkok",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi edit video AI dengan basis pengguna sangat besar, billing IAP belum di-routing resmi.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 1,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 89,
    estimasiGap: "Rp710 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0157",
    detailTambahan: "com.capcut.app",
  },
  {
    id: "esk-50",
    platform: "Remini",
    domisili: "Italia",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi peningkatan kualitas foto berbasis AI, popularitas stabil tinggi di Play Store.",
    dieskalasi: "24 Jun 2026",
    sisaHari: -3,
    sumberSinyal: "data.ai",
    confidenceScore: 50,
    estimasiGap: "Rp65 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0158",
    detailTambahan: "com.remini.app",
  },
  {
    id: "esk-51",
    platform: "Lensa AI",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi editor foto AI dari Prisma Labs, unduhan naik pasca tren avatar AI.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 0,
    sumberSinyal: "Similarweb",
    confidenceScore: 55,
    estimasiGap: "Rp98 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0159",
    detailTambahan: "com.prismalabs.lensa",
  },
  {
    id: "esk-52",
    platform: "FaceApp",
    domisili: "Siprus",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi transformasi wajah berbasis AI, basis pengguna besar dan stabil sejak lama.",
    dieskalasi: "17 Jun 2026",
    sisaHari: -9,
    sumberSinyal: "data.ai",
    confidenceScore: 33,
    estimasiGap: "Rp12 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0160",
    detailTambahan: "com.faceapp.app",
  },
  {
    id: "esk-53",
    platform: "Notion AI",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Fitur AI terintegrasi aplikasi produktivitas, unduhan tinggi dengan billing IAP belum resmi.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Sensor Tower",
    confidenceScore: 63,
    estimasiGap: "Rp155 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0161",
    detailTambahan: "com.notion.app",
  },
  {
    id: "esk-54",
    platform: "Speechify",
    domisili: "Amerika Serikat",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi text-to-speech AI, ranking naik di kategori produktivitas App Store.",
    dieskalasi: "21 Jun 2026",
    sisaHari: -5,
    sumberSinyal: "data.ai",
    confidenceScore: 41,
    estimasiGap: "Rp30 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0162",
    detailTambahan: "com.speechify.app",
  },
  {
    id: "esk-55",
    platform: "Photoroom",
    domisili: "Prancis",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi editor foto berbasis AI untuk e-commerce, adopsi tinggi di kalangan pelaku UMKM.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 5,
    sumberSinyal: "Similarweb",
    confidenceScore: 58,
    estimasiGap: "Rp82 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0163",
    detailTambahan: "com.photoroom.app",
  },
  {
    id: "esk-56",
    platform: "Vidnoz AI",
    domisili: "Singapura",
    institusi: "App Store / Play Store",
    catatan: "Aplikasi pembuat video avatar AI, ekspansi cepat di pasar Asia Tenggara.",
    dieskalasi: "30 Jun 2026",
    sisaHari: -1,
    sumberSinyal: "data.ai",
    confidenceScore: 44,
    estimasiGap: "Rp27 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0164",
    detailTambahan: "com.vidnoz.app",
  },
  {
    id: "esk-57",
    platform: "Jasper AI",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Volume transaksi langganan konten marketing domestik tinggi, status pemungut belum jelas.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "BI / PSP",
    confidenceScore: 66,
    estimasiGap: "Rp205 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0165",
    detailTambahan: "Xendit VA ****3391",
  },
  {
    id: "esk-58",
    platform: "Synthflow AI",
    domisili: "Jerman",
    institusi: "PSP",
    catatan: "Transaksi langganan voice agent AI melebihi ambang batas dua bulan berturut-turut.",
    dieskalasi: "23 Jun 2026",
    sisaHari: -6,
    sumberSinyal: "BI / PSP",
    confidenceScore: 37,
    estimasiGap: "Rp17 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0166",
    detailTambahan: "Midtrans Merchant ****7742",
  },
  {
    id: "esk-59",
    platform: "Gamma App",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Transaksi langganan pembuat presentasi AI naik pesat lewat gerbang pembayaran domestik.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 1,
    sumberSinyal: "Media Massa",
    confidenceScore: 52,
    estimasiGap: "Rp58 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0167",
    detailTambahan: "Doku Merchant ****2298",
  },
  {
    id: "esk-60",
    platform: "Framer AI",
    domisili: "Belanda",
    institusi: "PSP",
    catatan: "Transaksi langganan pembuat situs web AI dari pelaku bisnis lokal meningkat signifikan.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "BI / PSP",
    confidenceScore: 60,
    estimasiGap: "Rp110 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0168",
    detailTambahan: "BCA Virtual Account ****5567",
  },
  {
    id: "esk-61",
    platform: "Durable AI",
    domisili: "Kanada",
    institusi: "PSP",
    catatan: "Volume transaksi langganan pembuat situs UMKM naik tajam tanpa status pemungut jelas.",
    dieskalasi: "18 Jun 2026",
    sisaHari: -8,
    sumberSinyal: "Media Massa",
    confidenceScore: 31,
    estimasiGap: "Rp9 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0169",
    detailTambahan: "Xendit VA ****9013",
  },
  {
    id: "esk-62",
    platform: "Beautiful.ai",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Transaksi langganan pembuat presentasi otomatis dari korporat lokal terus meningkat.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 6,
    sumberSinyal: "BI / PSP",
    confidenceScore: 48,
    estimasiGap: "Rp38 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0170",
    detailTambahan: "Midtrans Merchant ****4456",
  },
  {
    id: "esk-63",
    platform: "Tome AI",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Transaksi langganan storytelling berbasis AI melebihi ambang batas domestik.",
    dieskalasi: "26 Jun 2026",
    sisaHari: -4,
    sumberSinyal: "Media Massa",
    confidenceScore: 35,
    estimasiGap: "Rp14 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0171",
    detailTambahan: "Doku Merchant ****6689",
  },
  {
    id: "esk-64",
    platform: "Chatbase",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Transaksi langganan chatbot AI kustom untuk bisnis lokal meningkat pesat.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "BI / PSP",
    confidenceScore: 57,
    estimasiGap: "Rp92 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0172",
    detailTambahan: "BCA Virtual Account ****7723",
  },
  {
    id: "esk-65",
    platform: "Voiceflow",
    domisili: "Kanada",
    institusi: "PSP",
    catatan: "Transaksi langganan platform desain voice/chat AI naik lewat gerbang pembayaran domestik.",
    dieskalasi: "20 Jun 2026",
    sisaHari: -10,
    sumberSinyal: "Media Massa",
    confidenceScore: 28,
    estimasiGap: "Rp6 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0173",
    detailTambahan: "Xendit VA ****1129",
  },
  {
    id: "esk-66",
    platform: "Airtable AI",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Fitur AI terintegrasi database kolaboratif, transaksi langganan korporat lokal meningkat.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "BI / PSP",
    confidenceScore: 63,
    estimasiGap: "Rp165 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0174",
    detailTambahan: "Midtrans Merchant ****8834",
  },
  {
    id: "esk-67",
    platform: "Zapier AI",
    domisili: "Amerika Serikat",
    institusi: "PSP",
    catatan: "Fitur otomasi berbasis AI, volume transaksi langganan bisnis digital lokal terus naik.",
    dieskalasi: "22 Jun 2026",
    sisaHari: -5,
    sumberSinyal: "Media Massa",
    confidenceScore: 40,
    estimasiGap: "Rp23 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0175",
    detailTambahan: "Doku Merchant ****3345",
  },
  {
    id: "esk-68",
    platform: "Make (Integromat)",
    domisili: "Republik Ceko",
    institusi: "PSP",
    catatan: "Transaksi langganan otomasi alur kerja AI dari tim engineering lokal meningkat signifikan.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "BI / PSP",
    confidenceScore: 46,
    estimasiGap: "Rp19 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0176",
    detailTambahan: "BCA Virtual Account ****2261",
  },
  {
    id: "esk-69",
    platform: "ChatGPT Plus",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Pembayaran langganan premium diproses langsung lewat jaringan kartu internasional tanpa melalui PSP domestik, escrow tidak dapat diterapkan.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 6,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 42,
    estimasiGap: "Rp95 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0177",
    detailTambahan: "Visa International ****4471",
  },
  {
    id: "esk-70",
    platform: "Claude Pro",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Transaksi langganan lintas batas terdeteksi lewat skema kartu global, belum ada mekanisme withholding di titik ini.",
    dieskalasi: "22 Jun 2026",
    sisaHari: -6,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 38,
    estimasiGap: "Rp70 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0178",
    detailTambahan: "Mastercard Global ****2298",
  },
  {
    id: "esk-71",
    platform: "Midjourney Pro",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Volume transaksi kartu internasional untuk langganan premium naik, jalur PSP domestik belum menangkap sinyal ini.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 45,
    estimasiGap: "Rp110 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0179",
    detailTambahan: "Visa International ****5588",
  },
  {
    id: "esk-72",
    platform: "ElevenLabs Pro",
    domisili: "Inggris",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Langganan premium dibayar langsung via kartu internasional, koordinasi dengan jaringan kartu diperlukan sebagai jalur cadangan.",
    dieskalasi: "18 Jun 2026",
    sisaHari: -9,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 30,
    estimasiGap: "Rp42 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0180",
    detailTambahan: "Mastercard Global ****7734",
  },
  {
    id: "esk-73",
    platform: "Runway Gen-3",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Transaksi kartu kredit lintas batas untuk fitur generatif video premium meningkat tajam dalam sebulan terakhir.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 5,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 48,
    estimasiGap: "Rp135 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0181",
    detailTambahan: "Visa International ****9021",
  },
  {
    id: "esk-74",
    platform: "Ideogram Plus",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Skema kartu internasional jadi satu-satunya jalur pembayaran, belum ada koordinasi withholding.",
    dieskalasi: "24 Jun 2026",
    sisaHari: -4,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 27,
    estimasiGap: "Rp19 Jt",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0182",
    detailTambahan: "Mastercard Global ****3312",
  },
  {
    id: "esk-75",
    platform: "Suno Pro",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Langganan musik AI premium diproses via kartu internasional, volume transaksi konsisten naik tiap bulan.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 40,
    estimasiGap: "Rp58 Jt",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0183",
    detailTambahan: "Visa International ****6650",
  },
  {
    id: "esk-76",
    platform: "HeyGen Pro",
    domisili: "Amerika Serikat",
    institusi: "Jaringan Kartu Internasional",
    catatan: "Transaksi kartu internasional untuk paket enterprise video AI terdeteksi tanpa jalur PSP domestik.",
    dieskalasi: "20 Jun 2026",
    sisaHari: -8,
    sumberSinyal: "Visa/Mastercard",
    confidenceScore: 25,
    estimasiGap: "Rp14 Jt",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0184",
    detailTambahan: "Mastercard Global ****1187",
  },
  {
    id: "esk-77",
    platform: "Kling AI",
    domisili: "Tiongkok",
    institusi: "Platform Iklan Digital",
    catatan: "Aktif beriklan di Meta Ads menargetkan pengguna Indonesia, skala kampanye jadi sinyal deteksi tambahan meski belum terverifikasi PSE.",
    dieskalasi: "5 Jul 2026",
    sisaHari: 3,
    sumberSinyal: "Meta Ads Library",
    confidenceScore: 34,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0185",
    detailTambahan: "Belum Terverifikasi",
  },
  {
    id: "esk-78",
    platform: "DeepSeek",
    domisili: "Tiongkok",
    institusi: "Platform Iklan Digital",
    catatan: "Kampanye iklan agresif di Google Ads untuk pasar Indonesia, dijadikan sinyal tambahan sambil menunggu registrasi PSE selesai.",
    dieskalasi: "6 Jul 2026",
    sisaHari: 2,
    sumberSinyal: "Google Ads Transparency",
    confidenceScore: 41,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0186",
    detailTambahan: "Belum Terverifikasi",
  },
  {
    id: "esk-79",
    platform: "Manus AI",
    domisili: "Tiongkok",
    institusi: "Platform Iklan Digital",
    catatan: "Iklan TikTok Ads menargetkan pengguna produktif Indonesia, volume kampanye jadi indikator skala operasi.",
    dieskalasi: "2 Jul 2026",
    sisaHari: -2,
    sumberSinyal: "TikTok Ads Library",
    confidenceScore: 29,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0187",
    detailTambahan: "Belum Terverifikasi",
  },
  {
    id: "esk-80",
    platform: "CapCut AI",
    domisili: "Tiongkok",
    institusi: "Platform Iklan Digital",
    catatan: "Setelah pendekatan awal, platform mulai kooperatif dan menyetujui program trusted-advertiser sambil proses registrasi berjalan.",
    dieskalasi: "1 Jul 2026",
    sisaHari: 12,
    sumberSinyal: "Meta Ads Library",
    confidenceScore: 55,
    estimasiGap: "Rp0 (insentif)",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0188",
    detailTambahan: "Trusted Advertiser (Kooperatif)",
  },
  {
    id: "esk-81",
    platform: "Perplexity AI",
    domisili: "Amerika Serikat",
    institusi: "Platform Iklan Digital",
    catatan: "Kampanye iklan pencarian AI menyasar segmen profesional Indonesia, jadi sinyal tambahan untuk prioritas verifikasi.",
    dieskalasi: "4 Jul 2026",
    sisaHari: 4,
    sumberSinyal: "Google Ads Transparency",
    confidenceScore: 37,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0189",
    detailTambahan: "Belum Terverifikasi",
  },
  {
    id: "esk-82",
    platform: "Character.AI",
    domisili: "Amerika Serikat",
    institusi: "Platform Iklan Digital",
    catatan: "Iklan menyasar segmen remaja lewat TikTok Ads, skala kampanye tinggi jadi prioritas pemantauan tambahan.",
    dieskalasi: "19 Jun 2026",
    sisaHari: -8,
    sumberSinyal: "TikTok Ads Library",
    confidenceScore: 26,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Sari Dewi, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0190",
    detailTambahan: "Belum Terverifikasi",
  },
  {
    id: "esk-83",
    platform: "Grok AI",
    domisili: "Amerika Serikat",
    institusi: "Platform Iklan Digital",
    catatan: "Aktif beriklan cross-platform, sudah menunjukkan itikad kooperatif dengan menyediakan data transparansi awal.",
    dieskalasi: "3 Jul 2026",
    sisaHari: 9,
    sumberSinyal: "Meta Ads Library",
    confidenceScore: 50,
    estimasiGap: "Rp0 (insentif)",
    petugasDjp: "Andi Pratama, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0191",
    detailTambahan: "Trusted Advertiser (Kooperatif)",
  },
  {
    id: "esk-84",
    platform: "You.com",
    domisili: "Amerika Serikat",
    institusi: "Platform Iklan Digital",
    catatan: "Kampanye iklan pencarian AI di Google Ads terdeteksi menyasar Indonesia, dijadikan sinyal tambahan pemantauan.",
    dieskalasi: "21 Jun 2026",
    sisaHari: -5,
    sumberSinyal: "Google Ads Transparency",
    confidenceScore: 31,
    estimasiGap: "Rp0 (soft leverage)",
    petugasDjp: "Rina Kartika, Tim Investigasi PMSE",
    nomorSurat: "SIGAP/ESK/2026/0192",
    detailTambahan: "Belum Terverifikasi",
  },
]

export function sisaWaktuInfo(sisaHari: number) {
  if (sisaHari < 0) {
    return {
      label: `Terlambat ${Math.abs(sisaHari)} hari`,
      color: "text-red-600",
      bg: "bg-red-50 border-red-200",
      dot: "bg-red-500",
    }
  }
  if (sisaHari <= 2) {
    return {
      label: `${sisaHari} hari lagi`,
      color: "text-red-600",
      bg: "bg-red-50 border-red-200",
      dot: "bg-red-500",
    }
  }
  if (sisaHari <= 5) {
    return {
      label: `${sisaHari} hari lagi`,
      color: "text-amber-600",
      bg: "bg-amber-50 border-amber-200",
      dot: "bg-amber-500",
    }
  }
  return {
    label: `${sisaHari} hari lagi`,
    color: "text-slate-600",
    bg: "bg-slate-50 border-slate-200",
    dot: "bg-slate-400",
  }
}

export function waktuInfoUntukInstitusi(sisaHari: number, gaya: GayaInstitusi) {
  if (gaya === "lembut") {
    if (sisaHari < 0) {
      return {
        label: `Menunggu respons · ${Math.abs(sisaHari)} hari`,
        color: "text-teal-700",
        bg: "bg-teal-50 border-teal-200",
        dot: "bg-teal-500",
      }
    }
    return {
      label: `${sisaHari} hari lagi`,
      color: "text-slate-600",
      bg: "bg-slate-50 border-slate-200",
      dot: "bg-slate-400",
    }
  }

  if (gaya === "netral") {
    if (sisaHari < 0) {
      return {
        label: `Terlambat ${Math.abs(sisaHari)} hari`,
        color: "text-amber-700",
        bg: "bg-amber-50 border-amber-200",
        dot: "bg-amber-500",
      }
    }
    return {
      label: `${sisaHari} hari lagi`,
      color: sisaHari <= 3 ? "text-amber-600" : "text-slate-600",
      bg: sisaHari <= 3 ? "bg-amber-50 border-amber-200" : "bg-slate-50 border-slate-200",
      dot: sisaHari <= 3 ? "bg-amber-500" : "bg-slate-400",
    }
  }

  return sisaWaktuInfo(sisaHari)
}